# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19a36b7e709cb95c9cd0183e9324d32a0d5896af1836abcc13b4ecdf2a34929b279e0ca8daf4780867a338f1458f7dba3ed40d56cd2c8248ec7b8176fa2d47a

test:
  secret_key_base: 44f1360bd1b79476a9c85ecdcefa50512313e3db874df71220a06e9ef53e084b11c9376a7214ea011c2ba0fb1317ae1d1fb961c98bf6e45d7d5e2dcc7d021ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
